### ISSUE TITLE
go through launch checklist on each page

### ISSUE THREAD

**Issue by cjwinchester** [statesman/ut-tower-shooting-50th#67]
Publishing checklist
=====================

An evolving checklist for publishing interactive projects.

## Prepping the files

- [x] Did you update `/public/includes/project-metrics.inc`?
- [x] Did you create a share image?
    - [x] Twitter: 755 x 378
    - [x] Facebook: 705 x 369
    - [x] Instagram: 612 x 612
- [x] Did you update your index (and other pages) with:
    - [x] Headline: Compelling and clickworthy?
    - [x] Title (make it SEO-friendly)
        - Might consider checking [Google Trends](https://www.google.com/trends/) to see what is searched.
        - Front-weight the title with keywords, but still make it headline-like.
        - Think full names of people, places and things.
    - [x] Description
    - [x] Thumbnail
    - [x] URL or `site_path` (used in sharing)
    - [x] Twitter (account used for sharing?)
- [x] Did you test all share links to make sure that:
    - [x] They work
    - [x] They resolve to to the correct URL
- [x] Did you get edited?
    - [x] By the reporter/editor you are working with
    - [x] By a data team peer

## Let the web desk know
- [ ] Send an email to statcom and interactives (both in TO field). Include the following:
    - [ ] The word "Published" in the subject line of the email
    - [ ] Headline that stands alone
    - [ ] Tease language that can be longer, but grab the reader
    - [ ] URL
    - [ ] Description of the story that the project goes with. The NewsEngin slug is nice to include. The URL to the story even better, if it has been published yet.
    - [ ] Attach your share image.
    - [ ] If there is a particular screenshot or image you like for the homepage rotator, crop to 615x385 and included it.

## Socialize it
- [ ] Post to AASInteractive social account. Use a tease image of some kind, if you can.
    - Go beyond straightforward: Use some call to action or interesting tidbit to draw attention.
    - Check for relevant keywords or hashtags that are trending, and include them.
- [ ] Offer FB post information to the social team at statcom.
    - A FB-friendly image is a plus.
- [ ] Post to your own account, and look to retweet your colleagues work.
